In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
train = pd.read_csv("traindata.csv")


In [3]:
train.head()

Unnamed: 0        ID  RevolvingUtilizationOfUnsecuredLines   age  \
0           0  117214.0                              0.128865  67.0   
1           1  144723.0                              0.179496  32.0   
2           2   27113.0                              0.528844  53.0   
3           3  142706.0                              0.018850  52.0   
4           4   14250.0                              0.569364  32.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   0.0   0.352588         5833.0   
1                                   1.0   0.245922         5700.0   
2                                   0.0   0.491452        11990.0   
3                                   0.0   0.299567         5083.0   
4                                   2.0   0.649189         4500.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                              8.0                      0.0   
1                             10.0                      1.0   
2                             15.0                      0.0   
3                             15.0                      0.0   
4                             10.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           1.0                                   0.0   
1                           0.0                                   0.0   
2                           3.0                                   0.0   
3                           2.0                                   0.0   
4                           1.0                                   2.0   

   NumberOfDependents  SeriousDlqin2yrs  
0                 0.0                 0  
1                 0.0                 0  
2                 3.0                 0  
3                 0.0                 0  
4                 2.0                 0

In [4]:
x_train=train[['RevolvingUtilizationOfUnsecuredLines','age','NumberOfTime30-59DaysPastDueNotWorse','DebtRatio','MonthlyIncome','NumberOfOpenCreditLinesAndLoans','NumberOfTimes90DaysLate','NumberRealEstateLoansOrLines','NumberOfTime60-89DaysPastDueNotWorse','NumberOfDependents']]
xtrain=np.array(x_train)
print(xtrain.shape)

(80546, 10)


In [5]:
y_train=train[['SeriousDlqin2yrs']]
ytrain=np.array(y_train)
print(ytrain.shape)

(80546, 1)


In [6]:
y_test = pd.read_csv('y_test 0513 cleaned.csv', header=None, usecols=[1])
#y_test=y_test.drop('1', axis=1)
y_test.columns=['y']
y_test.head()

y
0  0.0
1  0.0
2  0.0
3  0.0
4  0.0

In [7]:
X_test = pd.read_csv('X_test 0513 cleaned.csv')
X_test=X_test.drop('Unnamed: 0',axis=1)
X_test.head()

RevolvingUtilizationOfUnsecuredLines  age  \
0                              0.353590   66   
1                              0.024141   68   
2                              0.700250   27   
3                              0.023778   62   
4                              0.162417   65   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                     0   0.580712         4800.0   
1                                     1   0.580712         4800.0   
2                                     0   0.242380         2066.0   
3                                     0   0.214561         9600.0   
4                                     0   0.491388         6908.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                                9                        0   
1                               10                        0   
2                                4                        0   
3                                9                        0   
4                               10                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           2.0                                     0   
1                           1.0                                     0   
2                           0.0                                     0   
3                           1.0                                     1   
4                           2.0                                     0   

   NumberOfDependents  
0                   0  
1                   1  
2                   2  
3                   0  
4                   1

In [10]:
ytest=np.array(y_test)
xtest=np.array(X_test)

In [11]:
##Build the classification tree 
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.metrics import accuracy_score

In [13]:
from sklearn.metrics import confusion_matrix
## Baseline model: Use the numbers of times 90 days late directly to predict the outcome of SeriousDlqin2yrs
CM_baseline = confusion_matrix(ytest, xtest[:,-4])
print(CM_baseline)
print(accuracy_score(ytest,  xtest[:,-4]))

[[12905   453   137    62    25    10     9     6     2     2     1     1]
 [  911    33     9    10     3     0     2     1     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]]
0.8872582636126731


In [14]:
#Build a classification tree to fit the trainin set.
tree_D2Hawkeye = DecisionTreeClassifier(max_depth=6)

In [15]:
tree_D2Hawkeye.fit(xtrain, ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=6,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [16]:
##Print out the tree

import graphviz
dot_data = export_graphviz(tree_D2Hawkeye,feature_names= ['RevolvingUtilizationOfUnsecuredLines','age','NumberOfTime30-59DaysPastDueNotWorse','DebtRatio','MonthlyIncome','NumberOfOpenCreditLinesAndLoans','NumberOfTimes90DaysLate','NumberRealEstateLoansOrLines','NumberOfTime60-89DaysPastDueNotWorse','NumberOfDependents'], class_names = ['1','2','3','4','5']) 
tree_graph = graphviz.Source(dot_data) 
tree_graph.render("D2Hawkeye") 

'D2Hawkeye.pdf'

In [17]:
#Make predictions on the testing data set
ypredict = tree_D2Hawkeye.predict(xtest)


In [18]:
#create the confusion matrix on the out-of-sample test
CM_tree = confusion_matrix(ytest, ypredict)
print(CM_tree)

[[12686   927]
 [  899    70]]


In [20]:
#The testing overall accuracy
print(accuracy_score(ytest, ypredict))

0.8747771224797696


In [26]:
#Cross-validated Parameter tuning for the maximum depth of the tree
from sklearn.model_selection import GridSearchCV
param_grid = {'max_depth':range(1, 7)}
grid = GridSearchCV(DecisionTreeClassifier(random_state=0),param_grid=param_grid,cv=10)
grid.fit(xtrain, ytrain)
print(grid.best_params_)
print('Best Overal Accuracy: %.4f' %grid.best_score_)

{'max_depth': 6}
Best Overal Accuracy: 0.8710


In [28]:
best_rf=grid.best_estimator_
print('Validation Accuracy :: ',accuracy_score(ytest,best_rf.predict(xtest)))

Validation Accuracy ::  0.8747771224797696
